import localFont from "next/font/local";
import "./globals.css";

const anton = localFont({
  src: "/fonts/antonBold.ttf",
  variable: "--font-anton",
});

const geist = localFont({
  src:"fonts/Geist-Medium.ttf",
  variable: "--font-geist",
});

export const metadata = {
  title: "Mukul - Frontend Developer Protflio",
  description: "Generated by developer Mukul",
  icons: {
    icon: "Assets/Images/favicon.png",
  },
};


export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${anton.variable} ${geist.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" cz-shortcut-listen="true">{children}</body>
    </html>
  );
}
